version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      IRIS_USERNAME: demo
      IRIS_PASSWORD: demo
    restart: always
    hostname: iris
    ports:
      - 1972:1972
      - 52773:52773   
    volumes:
      - ./:/home/irisowner/dev     
